name: 'Store Docker Cache'
description: 'Save all Docker images to a compressed tarball and upload as artifact'

runs:
  using: composite
  steps:
    - name: Save Docker images
      shell: bash
      run: |
        echo "Saving all Docker images..."
        docker save $(docker images -q) -o docker-cache.tar
        echo "✓ Docker images saved to docker-cache.tar"

    - name: Compress Docker cache
      shell: bash
      run: |
        echo "Compressing docker-cache.tar with zstd..."
        zstd docker-cache.tar
        echo "✓ Compressed to docker-cache.tar.zst"
        rm docker-cache.tar

    - name: Upload Docker cache artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-cache
        path: docker-cache.tar.zst
        retention-days: 1
