name: 'Generate Report'
description: 'Generate summary report from test artifacts'
inputs:
  report_dir:
    description: 'Report directory path (e.g., reports/results/2025-11-18_12-34-56)'
    required: true
  report_file:
    description: 'Report file path (e.g., reports/results/2025-11-18_12-34-56/report.md)'
    required: true
  report_timestamp:
    description: 'Report timestamp (e.g., 2025-11-18_12-34-56)'
    required: true
  test_name:
    description: 'Name of the test run'
    required: false
    default: ''
  report_status:
    description: 'Status of the report (running or finished)'
    required: false
    default: 'running'
  add_report_summary:
    description: 'Whether to add a summary of the report to the step summary'
    required: false
    default: 'false'
  config_file:
    description: 'Path to config file'
    required: false
    default: 'config.json5'
runs:
  using: 'composite'
  steps:
    - name: Setup directories
      shell: bash
      run: |
        mkdir -p _repo

    - name: Checkout invenio-testrig repository
      uses: actions/checkout@v4
      with:
        path: _repo/repo

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: _repo/artifacts
        github-token: ${{ github.token }}
      env:
        ACTIONS_STEP_DEBUG: false

    - name: Generate report
      shell: bash
      run: |
        cd _repo/repo
        bash scripts/generate_and_push_report.sh "${{ inputs.report_dir }}" "${{ inputs.report_file }}" "${{ inputs.report_timestamp }}" "${{ inputs.test_name }}" "../artifacts" "20" "${{ inputs.report_status }}" "${{ inputs.config_file }}"

    - name: Add report summary
      shell: bash
      if: ${{ inputs.add_report_summary == 'true' }}
      run: |
        REPORT_URL="https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/${{ inputs.report_file }}"
        echo "## 📊 Report Generated" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The verification report is available at:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🔗 **[View Report]($REPORT_URL)**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Report Details:**" >> $GITHUB_STEP_SUMMARY
        echo "- Directory: \`${{ inputs.report_dir }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- Timestamp: \`${{ inputs.report_timestamp }}\`" >> $GITHUB_STEP_SUMMARY
        if [ -n "${{ inputs.test_name }}" ]; then
          echo "- Test Name: \`${{ inputs.test_name }}\`" >> $GITHUB_STEP_SUMMARY
        fi
