name: 'Setup Virtual Environment'
description: 'Create a virtual environment and install package dependencies'
inputs:
  package-path:
    description: 'Path to the package directory'
    required: true
  extras:
    description: 'Comma-separated list of package extras to install'
    required: false
    default: 'tests,opensearch2,s3,devs,s3fs,oaipmh,rdf,sparql,postgresql,admin,docs'
  python-version:
    description: 'Python version to use for the virtual environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Create virtual environment
      shell: bash
      run: |
        echo "SO_FAR_OK=0" >> $GITHUB_ENV
        cd ${{ inputs.package-path }}
        echo "🔧 Setting up virtual environment and installing dependencies"
        echo "::group::Creating virtual environment"
        uv venv --seed --python ${{ inputs.python-version }} .venv
        echo "::endgroup::"
        source .venv/bin/activate

        # Install the package with test dependencies
        echo "::group::Installing package with dependencies"
        uv pip install -e ".[${{ inputs.extras }}]"
        echo "::endgroup::"
        echo "✓ Virtual environment created and dependencies installed"
        echo "SO_FAR_OK=1" >> $GITHUB_ENV
